backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "img"

collections:
  - name: "paginas"
    label: "Páginas Principales"
    files:
      - label: "Inicio"
        name: "index"
        file: "index.html"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Cuerpo", name: "body", widget: "markdown"}
      - label: "Dieta"
        name: "dieta"
        file: "dieta.html"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Contenido", name: "body", widget: "markdown"}